GET http://localhost:3000/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNmY0ODBiNzdlOTUyMGIxODM1ZWEiLCJpYXQiOjE2NzA0OTA3MTIsImV4cCI6MTY3MTA5NTUxMn0.eIohI93X705cEif36pr1eoyQYwVC1R-Rd7sDIWPYX-Y

###

POST http://localhost:3000/signup
Accept: application/json
Content-Type: application/json

{
"name": "А",
"about": "С",
"avatar": "",
"email": "artem1@ya.ru",
"password": "artem1"
}
###

POST http://localhost:3000/signin
Accept: application/json
Content-Type: application/json

{
  "email": "test@ya.ru",
  "password": "test"
}
###

GET http://localhost:3000/users/61eade4c6d5acf558c42d9b8
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNmY0ODBiNzdlOTUyMGIxODM1ZWEiLCJpYXQiOjE2NzExMDIzMTMsImV4cCI6MTY3MTcwNzExM30.ATMifTn4PzhfLCrcT4yUWJXwWJCpJ_qPts7eyW8I77U

###

PATCH http://localhost:3000/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNmY0ODBiNzdlOTUyMGIxODM1ZWEiLCJpYXQiOjE2NzA0OTA3MTIsImV4cCI6MTY3MTA5NTUxMn0.eIohI93X705cEif36pr1eoyQYwVC1R-Rd7sDIWPYX-Y

{
  "name": "Александр С.",
  "about": "Инженер"
}

###

GET http://localhost:3000/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNmY0ODBiNzdlOTUyMGIxODM1ZWEiLCJpYXQiOjE2NzExMDA1MjAsImV4cCI6MTY3MTcwNTMyMH0.iJTtiFHck8efOlkeIPXcAgs4GgDqo1R3fydoW76lEuU

###

PATCH http://localhost:3000/users/me/avatar
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNmY0ODBiNzdlOTUyMGIxODM1ZWEiLCJpYXQiOjE2NzExMDA1MjAsImV4cCI6MTY3MTcwNTMyMH0.iJTtiFHck8efOlkeIPXcAgs4GgDqo1R3fydoW76lEuU
Content-Type: application/json

{
  "avatar": "https:/phonoteka.org/uploads/posts/2021-05/1622464154_11-phonoteka_org-p-kommunisticheskoe-budushchee-art-krasivo-13.jpg"
}

###

GET http://localhost:3000/cards
Accept: application/json

###

POST http://localhost:3000/cards
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNmY0ODBiNzdlOTUyMGIxODM1ZWEiLCJpYXQiOjE2NzExMDA1MjAsImV4cCI6MTY3MTcwNTMyMH0.iJTtiFHck8efOlkeIPXcAgs4GgDqo1R3fydoW76lEuU
Content-Type: application/json

{
  "name": "Лыжи",
  "link": "https://avatars.mds.yandex.net/get-marketcms/1668019/img-ae4ab14f-84bd-4866-99bf-c7188723e875.jpeg/optimize"
}
###

DELETE http://localhost:3000/cards/6391b92deb0dbe4d363a5fef
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwNzZkMWZlMGM0YjM1N2Q2ZWViMjciLCJpYXQiOjE2NzA0OTA1ODcsImV4cCI6MTY3MTA5NTM4N30.Zcc3pp0L4jvJ8IAYpymajUMX-7l3DjNIoI-VWNlml8Q

###

PUT http://localhost:3000/cards/6385b434603cdfc4632e9022/likes
Accept: application/json

###

DELETE http://localhost:3000/cards/6375b434603cdfc4632e9022/likes
Accept: application/json

###

PATCH http://localhost:3000/404
Accept: application/json

###